from ubuntu:16.04
run apt -y update
run apt -y upgrade
run apt -y install build-essential
run apt -y install git
run apt -y install vim
run apt -y install uuid-dev
run apt -y install pkg-config
run apt -y install python
