image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest
  TEST_BRANCH: testing

before_script:
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
  - echo "CONTAINER_TEST_IMAGE=$CONTAINER_TEST_IMAGE"
  - echo "CONTAINER_RELEASE_IMAGE=$CONTAINER_RELEASE_IMAGE"
  - echo "CI_PROJECT_URL=$CI_PROJECT_URL"

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - cd ubuntu
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - echo "docker push $CONTAINER_TEST_IMAGE"
    - docker push $CONTAINER_TEST_IMAGE
    - cd ..

test:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --rm -v $PWD:/root -w /root $CONTAINER_TEST_IMAGE ./test.sh

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - echo "docker push $CONTAINER_RELEASE_IMAGE"
    - docker push $CONTAINER_RELEASE_IMAGE
