# ex: softtabstop=2 shiftwidth=2 tabstop=2 expandtab

variables:
  BUILD_CONTAINER: ${CI_REGISTRY}/nextthingco/gadgetosd:unstable
  UPLOAD_CONTAINER: ${CI_REGISTRY}/nextthingco/ci-tools:unstable

stages:
  - build

build:
  image: docker:latest

  services:
    - docker:dind

  stage: build
  script:
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker pull $BUILD_CONTAINER
    - docker build -t $BUILD_CONTAINER dockerfiles/ubuntu
    - docker push $BUILD_CONTAINER

    - docker run --rm
      -v $PWD:/root
      -w /root
      $BUILD_CONTAINER
      make -s
    - docker pull $UPLOAD_CONTAINER
    - docker run
      -e GHVAR_AWS_ID=${GHVAR_AWS_ID}
      -e GHVAR_AWS_PW=${GHVAR_AWS_PW}
      -e GHVAR_AWS_REGION=${GHVAR_AWS_REGION}
      -e CI_PROJECT_NAME=${CI_PROJECT_NAME}
      -e CI_BUILD_REF_NAME=${CI_BUILD_REF_SLUG}
      -e CI_BUILD_ID=${CI_BUILD_ID}
      --rm -v $PWD:/upload -w /upload
      $UPLOAD_CONTAINER ci-s3-upload
      gadget

mac-build:
  stage: build
  tags: [alex-mac]
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cpack
    - ls
