/*
 * ex: softtabstop=4 shiftwidth=4 tabstop=4 expandtab
 *
 * Copyright (c) 2017 Next Thing Co
 * All rights reserved
 *
 * THIS FILE IS AUTOGENERATED - PLEASE CHANGE VERSION NUMBER IN CMAKE
 */

#define GADGETOSD_MAJOR  0
#define GADGETOSD_MINOR  0
#define GADGETOSD_PATCH  1
